RegisterServerEvent('sendAirOffer')
AddEventHandler('sendAirOffer', function(id, sender, pos1, pos2, tp)
	TriggerClientEvent('sendAirOffer', -1, id, sender, pos1, pos2, tp)
end)

RegisterServerEvent('acceptAirOffer')
AddEventHandler('acceptAirOffer', function(id, sender, pos1, pos2, tp)
	TriggerClientEvent('acceptAirOffer', -1, id, sender, pos1, pos2, tp)
end)

RegisterServerEvent('acceptAirOffer2')
AddEventHandler('acceptAirOffer2', function(id)
	TriggerClientEvent('acceptAirOffer2', -1, id)
end)

RegisterServerEvent('updateAirAnim')
AddEventHandler('updateAirAnim', function(id, m)
	TriggerClientEvent('updateAirAnim', -1, id, m)
end)
RegisterServerEvent('updateAirScore')
AddEventHandler('updateAirScore', function(id, ps, es)
	TriggerClientEvent('updateAirScore', -1, id, ps, es)
end)
RegisterServerEvent('sharePuck')
AddEventHandler('sharePuck', function(id, netid)
	TriggerClientEvent('sharePuck', -1, id, netid)
end)

RegisterServerEvent('finishAir')
AddEventHandler('finishAir', function(id)
	TriggerClientEvent('finishAir', -1, id)
end)
RegisterServerEvent('finishAir2')
AddEventHandler('finishAir2', function(id)
	TriggerClientEvent('finishAir2', -1, id)
end)

RegisterServerEvent('sendAirReward')
AddEventHandler('sendAirReward', function(id, amount, sender)
	TriggerClientEvent('sendAirReward', -1, id, amount, sender)
end)